### PR TITLE
Use noarch

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
could someone from @conda-forge/core merge this ?

**Comment by scopatz** [comment]
@jschueller - @jakirkham is the maintainer here, so there is no need to ping core :wink: I'd also suggest adding yourself as a maintainer, if this is a package you depend on :smile:

**Comment by jakirkham** [comment]
LGTM. Are you interested in helping maintain?

**Comment by jschueller** [comment]
not really, this one is not likely to move a lot

**Comment by jakirkham** [comment]
Thanks @jschueller :)

**Pull request merged**
